[phases.setup]
# Directly request the JDK 25 package from Nixpkgs
nixPkgs = ["jdk25"]

[phases.build]
# Manually specify your build command since we are bypassing the auto-provider
cmds = ["chmod +x ./mvnw", "./mvnw clean install -DskipTests"]

#[start]
## Define how to run your app
#cmd = "java -jar blablatwoApp/target/*.jar"
